openapi: 3.0.3
info:
  title: The Green Trip - Documentação de API
  description: |-
    Documentação da API construída para o projeto 'The Green Trip'. Construído segundo a OpenAPI 3.0. Mais sobre a OpenAPI e 
    Swagger em [https://swagger.io](https://swagger.io).
  version: 0.0.1
servers:
  - url: http://localhost:4001/
tags:
  - name: Utilizador
    description: Operações sobre os utilizadores da aplicação
  - name: Ponto de Interesse
    description: Tudo sobre o modelo principal do negócio
  - name: Evento
    description: Operações relacionadas com os eventos
  - name: Reserva
    description: Acesso às reservas criadas na aplicação
  - name: Recompensa
    description: Controlo sobre as recompensas 
  - name: Agente
    description: Controlo sobre utilizadores para mudar o seu tipo
paths:
  /pontoInteresse:
    post:
      tags:
        - Ponto de Interesse
      summary: Criar um produto novo
      description: Criação de um novo produto na base de dados, com base no requestBody
      operationId: postProduto
      responses:
        '200':
          description: Ponto de Interesse criado com sucesso
        '400': 
          description: Input invalido
        '403':
          description: Sem autorização
    get:
      tags:
        - Ponto de Interesse
      summary: Envia um ou mais pontos de interesse
      description: Envia um ou mais pontos de interesse, consoante o filtro enviado
      operationId: getPontoInteresse
      parameters:
        - name: nomePontoInteresse
          in: query
          required: false
          schema:
            type: string
        - name: pontoInteresseId
          in: query
          required: false
          schema:
            type: string
        - name: tipoInteresseId
          in: query
          required: false
          schema:
            type: string
        - name: freguesiaId
          in: query
          required: false
          schema:
            type: string
        - name: agenteTuristicoId
          in: query
          required: false
          schema:
            type: string
        - name: distritoId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Ponto's de Interesse enviado com sucesso
        '400':
          description: Input invalido
        '404':
          description: Ponto's de Interesse não existem
    put:
      tags:
        - Ponto de Interesse
      summary: Atualiza um ponto de interesse
      description: Atualiza um ponto de interesse especifico, com base no requestBody
      operationId: putPontoInteresse
      parameters:
        - name: pontoInteresseId
          in: query
          required: true
          schema:
            type: string
        - name: agenteTuristicoId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ponto de Interesse atualizado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Ponto de Interesse não existe
    patch:
      tags:
        - Ponto de Interesse
      summary: Atualiza o agente turistico de um ponto de interesse
      description: Atualiza o agente turistico de um ponto de interesse, com base no requestBody
      operationId: patchPontoInteresseAgente
      parameters:
        - name: pontoInteresseId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Agente turistico do ponto de Interesse atualizado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Ponto de Interesse não existe
    delete:
      tags:
        - Ponto de Interesse
      summary: Eliminar um ponto de interesse
      description: Elimina um ponto de interesse, consoante um id
      operationId: deletePontoInteresse
      parameters:
        - name: pontoInteresseId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ponto de Interesse eliminado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Ponto de Interesse não existe
  /tipoPontosInteresse:
    get:
      tags:
        - Ponto de Interesse
      summary: Envia um ou mais tipos de ponto de interesse
      description: Envia um ou mais tipos de ponto de interesse, consoante o filtro enviado
      operationId: getTipoPontoInteresse
      responses:
        '200':
          description: Tipo de ponto de interesse enviado com sucesso
        '400':
          description: Input invalido
  /utilizador:
    post:
      tags:
        - Utilizador
      summary: Criar um novo utilizador
      description: Criar utilizador, com base no requestBody
      operationId: postUser
      responses:
        '200':
          description: Utilizador criado com sucesso
        '400':
          description: Input invalido 
    get:
      tags:
        - Utilizador
      summary: Envia um ou mais utilizadores
      description: Envia um ou mais utilizadores, consoante o filtro usado
      operationId: getUtilizador
      parameters:
        - name: utilizadorId
          in: query
          required: false
          schema:
            type: string
        - name: tipoUtilizadorId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Utilizador/es enviada com sucesso
        '400':
          description: Input invalido
        '404':
          description: Utilizador/es não existem
    put:
      tags:
        - Utilizador
      summary: Atualiza as informações do utilizador
      description: Atualiza as informações do utilizador especifico, com base no requestBody
      operationId: putUtilizador
      parameters:
        - name: utilizadorId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilizador atualizado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Utilizador não existe
    patch:
      tags:
        - Utilizador
      summary: Tornar um utilizador em um agente turistico
      description: Tornar um utilizador em um agente turistico, com base no requestBody
      operationId: patchUtilizadorAgenteTuristico
      parameters:
        - name: utilizadorId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilizador mudado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Utilizador não existe
    delete:
      tags:
        - Utilizador
      summary: Eliminar um utilizador
      description: Elimina um utilizador especifico
      operationId: deleteUtilizador
      parameters:
        - name: utilizadorId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Utilizador eliminado com sucesso
        '400':
          description: Input invalido
        '403':
          description: Sem autorização
        '404':
          description: Utilizador não existe
  /reservas:
    get:
      tags:
        - Reserva
      summary: Envia uma ou mais reservas
      description: Envia uma ou mais reservas, consoante o filtro
      operationId: getReservas
      parameters:
        - name: utilizadorId
          in: query
          required: false
          schema:
            type: string
        - name: eventoId
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Reservas enviadas com sucesso
        '400':
          description: Input invalido
        '404':
          description: Reserva não existe
    post:
      tags:
        - Reserva
      summary: Adiciona uma reserva
      description: Adiciona uma reserva, efetuada pelo utilizador, com base no requestBody
      operationId: postReserva
      responses:
        '200':
          description: Reserva criada com sucesso
        '400':
          description: Input invalido
        '403':
          description: Necessita de ter o login efetuado
    put:
      tags:
        - Reserva
      summary: Atualiza um reserva ja efetuada
      description: Atualiza um reserva ja efetuada, com base no requestBody
      operationId: putReserva
      parameters:
        - name: utilizadorId
          in: query
          required: true
          schema:
            type: string
        - name: eventoId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Reserva atualizada com sucesso
        '400':
          description: Input invalido
        '403':
          description: Necessita de ter o login efetuado
        '404':
          description: Reserva não existe
  /evento:
    get:
      tags:
        - Evento
      summary: Enviar um ou mais eventos
      description: Enviar um ou mais eventos, consoante o filtro enviado
      operationId: getEvento
      parameters:
        - name: tipoEventoId
          in: query
          required: false
          schema:
            type: string
        - name: pontoInteresseId
          in: query
          required: false
          schema:
            type: string
  /tipoEventos:
    get:
      tags:
        - Evento
      summary: Envia um ou mais tipos de eventos
      description: Envia um ou mais tipos de eventos, consoante o filtro
      operationId: getTipoEventos
      responses:
        '200':
          description: Tipo de eventos enviado com sucesso
        '400':
          description: Input invalido
components:
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - token: []