name: Change env vars

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Change env
        uses: "DamianReeves/write-file-action@v1.0"
        with:
          path: .env
          write-mode: overwrite
          contents: |
            REACT_APP_PORT=4002

            REACT_APP_MODE="prod"
            REACT_APP_VERBOSE=1
            REACT_APP_LOGIN_OVERRIDE=0
            REACT_APP_MAX_RECORDS=10
            REACT_APP_IP="https://pi4-backend.herokuapp.com"
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          branch: main
          force: true
          message: "Overwritten by Github Actions"
